### PR TITLE
Add "close window" key binding to conky.config

### PR DESCRIPTION
**Pull request by eldelacajita**
`Super+Shift+q` is a rather important shortcut. As a new i3 user, I found it confusing to not see a tip on how to close windows. 

Feel free to reject this pull request if you think the new line should be added somewhere else!

### CODE REVIEW

**Comment by kgilmer** [comment]
Thank you for your pull request @eldelacajita !  I don't see anything wrong with your commit.  And I agree with you that it's confusing not to know how to close windows.  I have one concern however.  If you have a look at the [i3wm user guide](https://i3wm.org/docs/userguide.html#_closing_windows), this command may actually cause an application to be killed, meaning that any unsaved data would be lost.

This is one of the oddities of Linux (along w/ copy-paste), that there isn't consistency across applications.  I find typically it's either ctrl-w or ctrl-q will close an app.  But it can very and at this point in st, you have to type exit.  (It's odd that I never found this to be a bad user experience until others noted it.)

So, I would like the conky shortcut text to indicate that the action will "kill" and not "quit" the application, to be somewhat safer.  If you agree can you kindly update your PR?

**Comment by kgilmer** [comment]
Fixes #1.  Actually closing the terminal is ctrl-d.

**Comment by eldelacajita** [comment]
Oh, I see, it's more complex than I thought. I'll try to rephrase it!

**Comment by eldelacajita** [comment]
Yeah, this seems a bit unreliable. In most apps it works gracefully (asking if you want to save work, saving state, etc.), but there may be unexpected exceptions, like precisely the default terminal. The Gnome terminal, also included, works great with Super+Shift+q. 

How about something like this?
```
Ctrl+d$alignr Close active terminal
Super+Shift+q$alignr Kill active window
Ctrl+q (or other, by app)$alignr Quit active application
```

**Comment by eldelacajita** [comment]
Also, is there a reason why no system shutdown shortcut was added?

**Comment by downloadpizza** [comment]
@eldelacajita I think the terminal and ctrl-q shouldn't be on the help menu for i3, because they aren't handled by i3. Just wording it "killing" should be enough that users get that the windows die

**Comment by eldelacajita** [comment]
Done! Is it correct now?

**Comment by kgilmer** [comment]
Thanks for updating your patch @eldelacajita .  Looks good except I'd like the new entry to go into the bottom section (the one that starts with `Lock Screen`).  Regarding why there is no shortcut for system shutdown, it's just something I don't often do so didn't think to add it.  In fact there is another user who's implemented a shutdown menu in Rofi.  I haven't had a chance yet to integrate it for testing but may do so in the near future: https://github.com/regolith-linux/regolith-desktop/issues/45

**Comment by eldelacajita** [comment]
Wouldn't it make more sense to have all the window-related actions together and leave the last section just for lock screen, sleep and logout? I'm adding a commit to show what I mean. 

PS: This is my first attempt at making a PR and I'm having fun with it, but if you get bored and want to just edit the file yourself (which would have been the quick way to do this), feel free to do so and close this thread ;)

**Comment by kgilmer** [comment]
Agreed that this is better @eldelacajita .  Thank you for your improvement to Regolith!  If you'd like a Regolith sticker and care to send me a mailing address, send it to kgilmer@gmail.com and I'll send you one.

**Pull request merged**
